### ISSUE TITLE
Problem with Titanium 3.5.0 SDK

### ISSUE THREAD

**Issue by ottopic** [appcelerator-modules/ti.storekit#12]
Hi,
if I try to compile my app with this module I get this error:

[ERROR] :  2015-01-14 00:19:04.470 xcodebuild[28363:671359]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/myhome/Library/Developer/Xcode/DeveloperPortal%206.1.1.db).
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/MyApp.build/Debug-iphonesimulator/MyApp-universal.build/Objects-normal/x86_64/MyApp normal x86_64
[ERROR] :  (1 failure)

Without this module titanium compile fine. With 3.4.1 compile fine.

Do you have suggestion for me?

Best regards
Lorenzo

**Comment by ingo** [comment]
Which version of the module are you using?

**Comment by ottopic** [comment]
3.1.1 - It is the lastest available here http://gitt.io/component/ti.storekit . I have tried to recompile the module from this project but the problem is the same.

**Comment by ottopic** [comment]
@ingo Are you able to replicate the problem?

**Comment by jonalter** [comment]
@ottopic PR #13 should resolve your issue. In the PR there is a link to download the built module. Please test it out and let us know how it works for you.

**Comment by jonalter** [comment]
@ottopic did [3.1.2](https://github.com/appcelerator-modules/ti.storekit/releases/tag/ios-3.1.2) resolve your issue?

**Comment by ottopic** [comment]
@jonalter it works fine! Thanks

**Comment by jonalter** [comment]
@ottopic 
![Great!](http://forums.oce.leagueoflegends.com/board/attachment.php?attachmentid=4446&d=1380114992)
Closing.
