### ISSUE TITLE
requestReviewDialog not working

### ISSUE THREAD

**Issue by macasfaj** [appcelerator-modules/ti.storekit#29]
I have a problem. From my App I call this:

require('ti.storekit').requestReviewDialog();

It's great, the rate window appears, but if I select the stars, Send button is aways disabled.

Any help? Thanks.

**Comment by hansemannn** [comment]
That's all handled internally. Make sure to only run it on device and provisioned via TestFlight. See the [Apple docs](https://developer.apple.com/reference/storekit/skstorereviewcontroller/2851536-requestreview) for more infos.
