### ISSUE TITLE
I can't restore "single item" already purchased. Works in sendbox, not in production

### ISSUE THREAD

**Issue by Astrovic** [appcelerator-modules/ti.storekit#30]
Hello,
Can the module in sanboxbox work properly and in production no?
I did several sendbox tests for single item products. If a product has already been purchased, and I try to redo the purchase, it says correctly that the purchase has already been made. So if I use Restore, it works correctly and the `markProductAsPurchased()` method is invoked.
But it seems that production does not work. Users have bought products correctly, but the `markProductAsPurchased()` method does not seem to be invoked after the purchase, even using Restore.

**Comment by hansemannn** [comment]
Do you use the most recent version of the module? Also check your entitlements file, we don't do anything special there.

**Comment by macasfaj** [comment]
But @Astrovic is only purchasing. Entitlements file only is used for validating receipts. Or is ir necessary anyway?

**Comment by Astrovic** [comment]
I do not use a file entitlements. I should? I'm already using the latest version of the module (4.1.0), TiSDK 6.0.3.GA and Xcode8.3.

I did another test with the production version, and I discovered this:
If I make the purchase the first time, it runs fine, and the `markProductAsPurchased()` method is invoked correctly. However, if I remove the app and reinstall it, if I use the Buy button, it tell me that I have already purchased the product and that it will be downloaded for free (but nothing is done about it, and `markProductAsPurchased()` isn't invoked. If instead I use Restore, it tells me that _there are no purchases to restore_.

This is the Xcode device log when I try to restore (in the production version):

```
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(iTunesStore)[97] <Notice>: ISStoreURLOperation: Sending headers for <private>:
<private>
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TCP Conn Start [1454:0x134ee32a0]
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TCP Conn Event [1454:0x134ee32a0]: 1 Err(0)
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TCP Conn Connected [1454:0x134ee32a0]: Err(0)
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC Enabling TLS [1454:0x134ee32a0]
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TLS Event [1454:0x134ee32a0]: 2, Pending(0)
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TLS Event [1454:0x134ee32a0]: 11, Pending(0)
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TLS Event [1454:0x134ee32a0]: 14, Pending(0)
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TLS Trust Result [1454:0x134ee32a0]: 0
Apr 28 17:58:44 iPhone-7-Astrovic UserEventAgent(ThermalMonitor)[22] <Notice>: <Notice> LSController: <private>, fraction 0.000885
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TLS Event [1454:0x134ee32a0]: 20, Pending(0)
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TCP Conn Event [1454:0x134ee32a0]: 8 Err(0)
Apr 28 17:58:44 iPhone-7-Astrovic itunesstored(CFNetwork)[97] <Notice>: TIC TLS Handshake Complete [1454:0x134ee32a0]
Apr 28 17:58:45 iPhone-7-Astrovic itunesstored(iTunesStore)[97] <Notice>: ISStoreURLOperation: Received headers for <private>:
<private>
Apr 28 17:58:45 iPhone-7-Astrovic itunesstored(MobileInstallation)[97] <Notice>: <private>:AppReceipt:0:Success:Wrote app receipt
Apr 28 17:58:45 iPhone-7-Astrovic MyApp[5940] <Notice>: [INFO] Finished restoring completed transactions!
```

**Comment by hansemannn** [comment]
Sorry, I need a fully-isolated demo-code here, can you provide that? Maybe the sample has some usage-logic-errors for production, check against those as well (especially the payment/restore-flow).

**Comment by Astrovic** [comment]
Hi @hansemannn this is a fully-isolated demo-code: https://gist.github.com/Astrovic/99c55dcdb6409610f595f06b6b1c64cd

Basically I did just a few changes to the UI. The rest is identical to the example.
I have used this code for several years, and it has always worked. But, perhaps from iOS 10, some users have contacted me saying that they could not restore the products they already bought. I did a check, and in fact I found the same problem. So I updated the module, and the code, at the latest version, and I release a new app version last week (and has been regularly approved, and the status of the IAP is approved and clear for sale). But the restore of purchases does not work yet.

**Comment by hansemannn** [comment]
May be an Apple issue: https://forums.developer.apple.com/thread/17500

**Comment by macasfaj** [comment]
This issue comes from 2015....

**Comment by Astrovic** [comment]
This is not my problem, there are no log errors. I see only the message  "_There were no purchases to restore!_"

**Comment by Astrovic** [comment]
However, using the sandbox, the restore works perfectly. So the problem is just the restore in the production version.

**Comment by hansemannn** [comment]
@macasfaj Yeah I saw that. Just thought it may be back. I'll check it anyway, but not this week.

**Comment by Astrovic** [comment]
@hansemannn @macasfaj 
it seems ai itunes issue. Finally, after many days, i found this solution: 

> https://forums.developer.apple.com/thread/73247?q=in-app%20purchase%20non-consumable#213655
> 
> **These steps have worked for those affected:**
> 1) Sign out of the App Store on your device: in your Settings app > "iTunes & App Stores", tap your Apple ID, then "Sign Out" (don't sign back in yet)
> 2) Return to the app and again tap "Restore Previous Purchase". When prompted, sign back in.

**Comment by macasfaj** [comment]
Great :) thanks @Astrovic

**Comment by hansemannn** [comment]
Huuuuh, good to know! But really bad that those issues still happening with iTunes Connect, crazy. Thanks for the discussion guys!
